version 0.6-7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -627,6 +627,7 @@ ORTED
 EGREP
 GREP
 CPP
+PKG_CONFIG
 OBJEXT
 EXEEXT
 ac_ct_CC
@@ -2940,13 +2941,74 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 if test "X$CC" = "X" ; then
-# Our best guess...
-CC="gcc -std=gnu99"
+	# Our best guess...
+	CC="gcc -std=gnu99"
 fi
 
 if test -z "$MPI_ROOT" ; then
-  for d in /opt/lib /usr/lib /usr /usr/local/lib /usr/local \
-          /usr/lib64/mpi/gcc/openmpi; do
+	#Use pkg-config to find openmpi
+	# Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PKG_CONFIG" >&5
+$as_echo "$PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+
+	if test -n "${PKG_CONFIG}"; then
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: checking if pkg-config knows about OpenMPI" >&5
+$as_echo_n "checking if pkg-config knows about OpenMPI... " >&6; }
+		if "${PKG_CONFIG}" --exists ompi; then
+			{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+			MPITYPE="OPENMPI"
+			MPI_ROOT="NONEED"
+
+			OMPI_INCLUDE_PATH=`"${PKG_CONFIG}" --cflags ompi`
+			OMPI_LIBS=`"${PKG_CONFIG}" --libs ompi`
+		else
+			{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+		fi
+	fi
+fi
+
+if test -z "$MPI_ROOT" ; then
+  for d in /opt/lib /usr/lib /usr /usr/lib/x86_64-linux-gnu/openmpi \
+          /usr/local/lib /usr/local /usr/lib64/mpi/gcc/openmpi; do
     if test -f $d/include/mpi.h && test -d $d/lib/openmpi; then
       echo "I am here $d and it is OpenMPI"
       MPI_ROOT=$d
@@ -3013,43 +3075,44 @@ if test -z "$MPI_ROOT" ; then
   done
 fi
 
-if test -n "$MPI_ROOT"; then
-	#guess MPITYPE if it is unknown and user supplies MPI_ROOT
-	if test $MPITYPE = "UNKNOWN" ; then
-		if test -d ${MPI_ROOT}/openmpi; then
-			MPITYPE="OPENMPI"
-		elif test -d ${MPI_ROOT}/lib/openmpi; then
-			MPITYPE="OPENMPI"
-		elif test -d ${MPI_ROOT}/lib64/openmpi; then
-		 	MPITYPE="OPENMPI"
-		elif test -f ${MPI_ROOT}/lib/liblam.so; then
-		 	MPITYPE="LAM"
-		elif test -d ${MPI_ROOT}/lib/lam; then
-		 	MPITYPE="LAM"
-		elif test -d ${MPI_ROOT}/lib64/lam; then
-		 	MPITYPE="LAM"
-		elif test -f ${MPI_ROOT}/lib/libmpich.a; then
-		 	MPITYPE="MPICH"
-		elif test -f ${MPI_ROOT}/lib64/libmpich.a; then
-		 	MPITYPE="MPICH"
+if test "$MPI_ROOT" != "NONEED"; then
+	if test -n "$MPI_ROOT"; then
+		#guess MPITYPE if it is unknown and user supplies MPI_ROOT
+		if test $MPITYPE = "UNKNOWN" ; then
+			if test -d ${MPI_ROOT}/openmpi; then
+				MPITYPE="OPENMPI"
+			elif test -d ${MPI_ROOT}/lib/openmpi; then
+				MPITYPE="OPENMPI"
+			elif test -d ${MPI_ROOT}/lib64/openmpi; then
+				MPITYPE="OPENMPI"
+			elif test -f ${MPI_ROOT}/lib/liblam.so; then
+				MPITYPE="LAM"
+			elif test -d ${MPI_ROOT}/lib/lam; then
+				MPITYPE="LAM"
+			elif test -d ${MPI_ROOT}/lib64/lam; then
+				MPITYPE="LAM"
+			elif test -f ${MPI_ROOT}/lib/libmpich.a; then
+				MPITYPE="MPICH"
+			elif test -f ${MPI_ROOT}/lib64/libmpich.a; then
+				MPITYPE="MPICH"
+			fi
 		fi
-	fi
-    echo "Trying to find mpi.h ..."
-    if test -f ${MPI_ROOT}/include/mpi.h; then
-         echo "Found in ${MPI_ROOT}/include"
-         MPI_INCLUDE_PATH="${MPI_ROOT}/include"
-    elif test -f ${MPI_ROOT}/include/openmpi/mpi.h; then
-         echo "Found in ${MPI_ROOT}/include/openmpi"
-         MPI_INCLUDE_PATH="${MPI_ROOT}/include/openmpi"
-    elif test -f ${MPI_ROOT}/include/lam/mpi.h; then
-         echo "Found in ${MPI_ROOT}/include/lam"
-         MPI_INCLUDE_PATH="${MPI_ROOT}/include/lam"
-    else
-         echo "Cannot find mpi.h header file"
-         echo "Please use --with-mpi=/path/to/mpi or specify the environment variable MPI_ROOT"
-         exit 1
-    fi
-else
+		echo "Trying to find mpi.h ..."
+		if test -f ${MPI_ROOT}/include/mpi.h; then
+			echo "Found in ${MPI_ROOT}/include"
+			MPI_INCLUDE_PATH="${MPI_ROOT}/include"
+		elif test -f ${MPI_ROOT}/include/openmpi/mpi.h; then
+			echo "Found in ${MPI_ROOT}/include/openmpi"
+			MPI_INCLUDE_PATH="${MPI_ROOT}/include/openmpi"
+		elif test -f ${MPI_ROOT}/include/lam/mpi.h; then
+			echo "Found in ${MPI_ROOT}/include/lam"
+			MPI_INCLUDE_PATH="${MPI_ROOT}/include/lam"
+		else
+			echo "Cannot find mpi.h header file"
+			echo "Please use --with-mpi=/path/to/mpi or specify the environment variable MPI_ROOT"
+			exit 1
+		fi
+	else
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -3456,36 +3519,36 @@ else
 fi
 
 
-fi
+	fi
 
-echo "Trying to find libmpi.so or libmpich.a ..."
-if test -f ${MPI_ROOT}/lib/libmpi.so; then
+	echo "Trying to find libmpi.so or libmpich.a ..."
+	if test -f ${MPI_ROOT}/lib/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib"
         MPI_LIBPATH="${MPI_ROOT}/lib"
-elif test -f ${MPI_ROOT}/libmpi.so; then
-        echo "Found libmpi in ${MPI_ROOT}"
+	elif test -f ${MPI_ROOT}/libmpi.so; then
+		        echo "Found libmpi in ${MPI_ROOT}"
         MPI_LIBPATH="${MPI_ROOT}"
-elif test -f ${MPI_ROOT}/lib/openmpi/libmpi.so; then
+	elif test -f ${MPI_ROOT}/lib/openmpi/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib/openmpi"
         MPI_LIBPATH="${MPI_ROOT}/lib/openmpi"
-elif test -f ${MPI_ROOT}/lib64/openmpi/libmpi.so; then
+	elif test -f ${MPI_ROOT}/lib64/openmpi/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib64/openmpi"
         MPI_LIBPATH="${MPI_ROOT}/lib64/openmpi"
-elif test -f ${MPI_ROOT}/lib64/libmpi.so; then
+	elif test -f ${MPI_ROOT}/lib64/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib64"
         MPI_LIBPATH="${MPI_ROOT}/lib64"
-elif test -f ${MPI_ROOT}/lib/lam/libmpi.so; then
+	elif test -f ${MPI_ROOT}/lib/lam/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib/lam"
         MPI_LIBPATH="${MPI_ROOT}/lib/lam"
-	MPI_INCL2="-I${MPI_INCLUDE_PATH}/32"
-elif test -f ${MPI_ROOT}/lib64/lam/libmpi.so; then
+		MPI_INCL2="-I${MPI_INCLUDE_PATH}/32"
+	elif test -f ${MPI_ROOT}/lib64/lam/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib64/lam"
         MPI_LIBPATH="${MPI_ROOT}/lib64/lam"
-	MPI_INCL2="-I${MPI_INCLUDE_PATH}/64"
-elif test -f ${MPI_ROOT}/lib/libmpich.so; then
+		MPI_INCL2="-I${MPI_INCLUDE_PATH}/64"
+	elif test -f ${MPI_ROOT}/lib/libmpich.so; then
         echo "Found libmpich in ${MPI_ROOT}/lib"
         MPI_LIBPATH="${MPI_ROOT}/lib"
-	ac_fn_c_check_decl "$LINENO" "MPICH2" "ac_cv_have_decl_MPICH2" "#include <mpi.h>
+		ac_fn_c_check_decl "$LINENO" "MPICH2" "ac_cv_have_decl_MPICH2" "#include <mpi.h>
 "
 if test "x$ac_cv_have_decl_MPICH2" = xyes; then :
   ac_have_decl=1
@@ -3514,10 +3577,10 @@ if test $ac_have_decl = 1; then :
     MPI_DEFS="-DMPI2"
 fi
 
-elif test -f ${MPI_ROOT}/lib64/libmpich.a; then
+	elif test -f ${MPI_ROOT}/lib64/libmpich.a; then
         echo "Found libmpich in ${MPI_ROOT}/lib64"
         MPI_LIBPATH="${MPI_ROOT}/lib64"
-	ac_fn_c_check_decl "$LINENO" "MPICH2" "ac_cv_have_decl_MPICH2" "#include <mpi.h>
+		ac_fn_c_check_decl "$LINENO" "MPICH2" "ac_cv_have_decl_MPICH2" "#include <mpi.h>
 "
 if test "x$ac_cv_have_decl_MPICH2" = xyes; then :
   ac_have_decl=1
@@ -3546,8 +3609,8 @@ if test $ac_have_decl = 1; then :
     MPI_DEFS="-DMPI2"
 fi
 
-else
-    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for main in -lmpi" >&5
+	else
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for main in -lmpi" >&5
 $as_echo_n "checking for main in -lmpi... " >&6; }
 if ${ac_cv_lib_mpi_main+:} false; then :
   $as_echo_n "(cached) " >&6
@@ -3585,6 +3648,7 @@ else
 
 fi
 
+	fi
 fi
 
 if test "$MPITYPE" = "OPENMPI" ; then
@@ -3764,11 +3828,19 @@ if test "$MPITYPE" = "OPENMPI" -o "$MPITYPE" = "LAM" -o "$MPITYPE" = "MPICH2" -o
   MPI_DEFS="-DMPI2"
 fi
 
-PKG_CPPFLAGS="-I${MPI_INCLUDE_PATH} ${MPI_INCL2} ${MPI_DEFS} -D${MPITYPE}"
+if test "$MPI_ROOT" = "NONEED"; then
+	PKG_CPPFLAGS="${OMPI_INCLUDE_PATH} ${MPI_DEFS} -D${MPITYPE}"
+else
+	PKG_CPPFLAGS="-I${MPI_INCLUDE_PATH} ${MPI_INCL2} ${MPI_DEFS} -D${MPITYPE}"
+fi
 
 case "$MPITYPE" in
   OPENMPI)
-    PKG_LIBS="-L${MPI_LIBPATH} -lmpi ${MPI_LIBS}"
+    if test "$MPI_ROOT" = "NONEED"; then
+		PKG_LIBS="${OMPI_LIBS} ${MPI_LIBS}"
+	else
+		PKG_LIBS="-L${MPI_LIBPATH} -lmpi ${MPI_LIBS}"
+	fi
     ;;
   LAM)
     PKG_LIBS="-L${MPI_LIBPATH} -lmpi -llam ${MPI_LIBS}"
