version 0.5-8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -660,8 +660,8 @@ OBJEXT
 CPP
 GREP
 EGREP
-PKG_LIBS
 PKG_CPPFLAGS
+PKG_LIBS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1242,7 +1242,13 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-   --with-mpi=/opt/lib32/usr/lib          Location of MPI library.
+  --with-Rmpi-include=INCLUDE_PATH
+                          location of MPI header files
+  --with-Rmpi-libpath=LIB_PATH
+                          location of MPI library files
+  --with-Rmpi-type=MPI_TYPE
+                          the type of MPI: OPENMPI, LAM or MPICH
+  --with-mpi=LIB_PATH     location of top-level MPI directory
 
 Some influential environment variables:
   CC          C compiler command
@@ -1677,6 +1683,92 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+## One way is to specify both include and lib paths
+
+# Check whether --with-Rmpi-include was given.
+if test "${with_Rmpi_include+set}" = set; then
+  withval=$with_Rmpi_include; mpi_include_path=$withval
+fi
+
+if test -n "${mpi_include_path}" ; then
+   MPI_INCLUDE_PATH="${mpi_include_path}"
+   if test ! -f "${MPI_INCLUDE_PATH}/mpi.h"; then
+     { { echo "$as_me:$LINENO: error: Value of --with-Rmpi-include does not contain mpi.h" >&5
+echo "$as_me: error: Value of --with-Rmpi-include does not contain mpi.h" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+else
+  if test -n "${RMPI_INCLUDE}" ; then
+    MPI_INCLUDE_PATH="${RMPI_INCLUDE}"
+    if test ! -f "${MPI_INCLUDE_PATH}/mpi.h"; then
+      { { echo "$as_me:$LINENO: error: Value of RMPI_INCLUDE does not contain mpi.h" >&5
+echo "$as_me: error: Value of RMPI_INCLUDE does not contain mpi.h" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    echo "setting mpi include path from RMPI_INCLUDE"
+  fi
+fi
+
+
+# Check whether --with-Rmpi-libpath was given.
+if test "${with_Rmpi_libpath+set}" = set; then
+  withval=$with_Rmpi_libpath; mpi_lib_path=$withval
+fi
+
+if test -n "${mpi_lib_path}" ; then
+   MPI_LIBPATH="${mpi_lib_path}"
+else
+  if test -n "${RMPI_LIB_PATH}" ; then
+    MPI_LIBPATH="${RMPI_LIB_PATH}"
+    echo "setting mpi lib path from RMPI_LIB_PATH"
+  fi
+fi
+
+if test -n "${MPI_INCLUDE_PATH}" -a -z "${MPI_LIBPATH}" ; then
+  { { echo "$as_me:$LINENO: error: Must specify both the include and lib paths" >&5
+echo "$as_me: error: Must specify both the include and lib paths" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${MPI_INCLUDE_PATH}" -a -n "${MPI_LIBPATH}" ; then
+  { { echo "$as_me:$LINENO: error: Must specify both the include and lib paths" >&5
+echo "$as_me: error: Must specify both the include and lib paths" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+MPITYPE="UNKNOWN"
+
+
+# Check whether --with-Rmpi-type was given.
+if test "${with_Rmpi_type+set}" = set; then
+  withval=$with_Rmpi_type; mpi_type=$withval
+fi
+
+if test -n "${mpi_type}" ; then
+   MPITYPE="${mpi_type}"
+else
+  if test -n "${RMPI_TYPE}" ; then
+     MPITYPE="${RMPI_TYPE}"
+  fi
+fi
+
+if test -z "${MPI_INCLUDE_PATH}" ; then
+
+## another way is to specify MPI_ROOT, perhaps via --with-mpi
+
+# Check whether --with-mpi was given.
+if test "${with_mpi+set}" = set; then
+  withval=$with_mpi;    if test "${withval}" != "no"; then
+        MPI_ROOT=${withval}
+        MPI_INCLUDE_PATH="${MPI_ROOT}/include"
+        LDFLAGS="$LDFLAGS -L${withval}/lib"
+        CPPFLAGS="$CPPFLAGS -I${withval}/include"
+    fi
+
+fi
+
+
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -2598,65 +2690,59 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-# Check whether --with-mpi was given.
-if test "${with_mpi+set}" = set; then
-  withval=$with_mpi;    if test "${withval}" != no; then
-        MPI_ROOT=${withval}
-        MPI_INCLUDE="-I${MPI_ROOT}/include"
-        LDFLAGS="$LDFLAGS -L${withval}/lib"
-        CFLAGS="$CFLAGS -I${withval}/include"
-    fi
-
-fi
-
-
-MPITYPE="UNKNOWN"
-
-if  [ "$MPI_ROOT" = "" ] ; then
+if test -z "$MPI_ROOT" ; then
   for d in /opt/lib /usr/lib /usr /usr/local/lib /usr/local; do
     if test -f $d/include/mpi.h && test -d $d/lib/openmpi; then
       echo "I am here $d and it is OpenMPI"
       MPI_ROOT=$d
-  	  MPITYPE="OPENMPI"
+      MPITYPE="OPENMPI"
       break
     elif test -f $d/include/openmpi/mpi.h && test -d $d/lib/openmpi; then
       echo "I am here $d and it is OpenMPI"
       MPI_ROOT=$d
-  	  MPITYPE="OPENMPI"
+      MPITYPE="OPENMPI"
+      MPI_INCLUDE_PATH=$d/include/openmpi
       break
     elif test -f $d/include/openmpi/mpi.h && test -d $d/lib64/openmpi; then
       echo "I am here $d and it is OpenMPI"
       MPI_ROOT=$d
-  	  MPITYPE="OPENMPI"
+      MPITYPE="OPENMPI"
+      MPI_INCLUDE_PATH=$d/include/openmpi
       break
     elif test -f $d/openmpi/include/mpi.h && test -d $d/openmpi/lib; then
       echo "I am here $d/openmpi and it is OpenMPI"
       MPI_ROOT=$d/openmpi
-          MPITYPE="OPENMPI"
+      MPITYPE="OPENMPI"
+      MPI_INCLUDE_PATH=$d/include/openmpi
       break
    elif test -f $d/lam/include/mpi.h && test -f $d/lam/lib/libmpi.so; then
       echo "I am here $d/lam and it is LAM"
       MPI_ROOT=$d/lam
-	  MPITYPE="LAM"
+      MPITYPE="LAM"
+      MPI_INCLUDE_PATH=$d/include/lam
       break
-	elif test -f $d/include/lam/mpi.h && test -f $d/lib/lam/libmpi.so; then
-	  echo "I am here $d and it is LAM"
-	  MPI_ROOT=$d
-	  MPITYPE="LAM"
-	  break
-	elif test -f $d/include/lam/mpi.h && test -f $d/lib64/lam/libmpi.so; then
-	  echo "I am here $d and it is LAM"
-	  MPI_ROOT=$d
-	  MPITYPE="LAM"
-	  break
+   elif test -f $d/include/lam/mpi.h && test -f $d/lib/lam/libmpi.so; then
+      echo "I am here $d and it is LAM"
+      MPI_ROOT=$d
+      MPITYPE="LAM"
+      MPI_INCLUDE_PATH=$d/include/lam
+      break
+    elif test -f $d/include/lam/mpi.h && test -f $d/lib64/lam/libmpi.so; then
+      echo "I am here $d and it is LAM"
+      MPI_ROOT=$d
+      MPITYPE="LAM"
+      MPI_INCLUDE_PATH=$d/include/lam
+      break
     elif test -f $d/mpich/include/mpi.h; then
       echo "I am here $d/mpich and it is MPICH"
       MPI_ROOT=$d/mpich
-	  MPITYPE="MPICH"
+      MPITYPE="MPICH"
+      MPI_INCLUDE_PATH=$d/mpich/include
       break
     elif test -f $d/mpi/include/mpi.h; then
       echo "I am here $d/mpi"
       MPI_ROOT=$d/mpi
+      MPI_INCLUDE_PATH=$d/mpi/include
       break
     elif test -f $d/include/mpi.h; then
       echo "I am here $d"
@@ -2668,8 +2754,10 @@ fi
 
 if test -n "$MPI_ROOT"; then
 	#guess MPITYPE if it is unknown and user supplies MPI_ROOT
-	if  [ $MPITYPE = "UNKNOWN" ]; then
-		if test -d ${MPI_ROOT}/lib/openmpi; then
+	if test $MPITYPE = "UNKNOWN" ; then
+		if test -d ${MPI_ROOT}/openmpi; then
+			MPITYPE="OPENMPI"
+		elif test -d ${MPI_ROOT}/lib/openmpi; then
 			MPITYPE="OPENMPI"
 		elif test -d ${MPI_ROOT}/lib64/openmpi; then
 		 	MPITYPE="OPENMPI"
@@ -2685,18 +2773,18 @@ if test -n "$MPI_ROOT"; then
 		 	MPITYPE="MPICH"
 		fi
 	fi
-    echo "Try to find mpi.h ..."
+    echo "Trying to find mpi.h ..."
     if test -f ${MPI_ROOT}/include/mpi.h; then
          echo "Found in ${MPI_ROOT}/include"
-         MPI_INCLUDE="-I${MPI_ROOT}/include"
+         MPI_INCLUDE_PATH="${MPI_ROOT}/include"
     elif test -f ${MPI_ROOT}/include/openmpi/mpi.h; then
          echo "Found in ${MPI_ROOT}/include/openmpi"
-         MPI_INCLUDE="-I${MPI_ROOT}/include/openmpi"
+         MPI_INCLUDE_PATH="${MPI_ROOT}/include/openmpi"
     elif test -f ${MPI_ROOT}/include/lam/mpi.h; then
          echo "Found in ${MPI_ROOT}/include/lam"
-         MPI_INCLUDE="-I${MPI_ROOT}/include/lam"
+         MPI_INCLUDE_PATH="${MPI_ROOT}/include/lam"
     else
-         echo "Cannot find mpi head file"
+         echo "Cannot find mpi.h header file"
          echo "Please use --with-mpi=/path/to/mpi or specify the environment variable MPI_ROOT"
          exit 1
     fi
@@ -3463,31 +3551,41 @@ fi
 echo "${ECHO_T}$ac_cv_header_mpi_h" >&6; }
 
 fi
+if test $ac_cv_header_mpi_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: \"Cannot find mpi.h header file\"" >&5
+echo "$as_me: error: \"Cannot find mpi.h header file\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 fi
 
-echo "Try to find libmpi.so or libmpich.a"
+echo "Trying to find libmpi.so or libmpich.a ..."
 if test -f ${MPI_ROOT}/lib/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib"
-        MPI_LIBS="-L${MPI_ROOT}/lib -lmpi"
+        MPI_LIBPATH="${MPI_ROOT}/lib"
+elif test -f ${MPI_ROOT}/libmpi.so; then
+        echo "Found libmpi in ${MPI_ROOT}"
+        MPI_LIBPATH="${MPI_ROOT}"
 elif test -f ${MPI_ROOT}/lib/openmpi/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib/openmpi"
-        MPI_LIBS="-L${MPI_ROOT}/lib/openmpi -lmpi"
+        MPI_LIBPATH="${MPI_ROOT}/lib/openmpi"
 elif test -f ${MPI_ROOT}/lib64/openmpi/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib64/openmpi"
-        MPI_LIBS="-L${MPI_ROOT}/lib64/openmpi -lmpi"
+        MPI_LIBPATH="${MPI_ROOT}/lib64/openmpi"
 elif test -f ${MPI_ROOT}/lib/lam/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib/lam"
-        MPI_LIBS="-L${MPI_ROOT}/lib/lam -lmpi"
-	MPI_INCLUDE="${MPI_INCLUDE} ${MPI_INCLUDE}/32"
+        MPI_LIBPATH="${MPI_ROOT}/lib/lam"
+	MPI_INCL2="-I${MPI_INCLUDE_PATH}/32"
 elif test -f ${MPI_ROOT}/lib64/lam/libmpi.so; then
         echo "Found libmpi in ${MPI_ROOT}/lib64/lam"
-        MPI_LIBS="-L${MPI_ROOT}/lib64/lam -lmpi"
-	MPI_INCLUDE="${MPI_INCLUDE} ${MPI_INCLUDE}/64"
+        MPI_LIBPATH="${MPI_ROOT}/lib64/lam"
+	MPI_INCL2="-I${MPI_INCLUDE_PATH}/64"
 elif test -f ${MPI_ROOT}/lib/libmpich.a; then
         echo "Found libmpich in ${MPI_ROOT}/lib"
-        MPI_LIBS="-L${MPI_ROOT}/lib -lmpich"
+        MPI_LIBPATH="${MPI_ROOT}/lib"
 	{ echo "$as_me:$LINENO: checking whether MPICH2 is declared" >&5
 echo $ECHO_N "checking whether MPICH2 is declared... $ECHO_C" >&6; }
 if test "${ac_cv_have_decl_MPICH2+set}" = set; then
@@ -3547,7 +3645,7 @@ cat >>confdefs.h <<_ACEOF
 #define HAVE_DECL_MPICH2 1
 _ACEOF
 
-  MPI_DEPS="-DMPI2"
+  MPI_DEFS="-DMPI2"
 else
   cat >>confdefs.h <<_ACEOF
 #define HAVE_DECL_MPICH2 0
@@ -3614,7 +3712,7 @@ cat >>confdefs.h <<_ACEOF
 #define HAVE_DECL_MPICH2 1
 _ACEOF
 
-  MPI_DEPS="-DMPI2"
+  MPI_DEFS="-DMPI2"
 else
   cat >>confdefs.h <<_ACEOF
 #define HAVE_DECL_MPICH2 0
@@ -3626,7 +3724,7 @@ fi
 
 elif test -f ${MPI_ROOT}/lib64/libmpich.a; then
         echo "Found libmpich in ${MPI_ROOT}/lib64"
-        MPI_LIBS="-L${MPI_ROOT}/lib64 -lmpich"
+        MPI_LIBPATH="${MPI_ROOT}/lib64"
 	{ echo "$as_me:$LINENO: checking whether MPICH2 is declared" >&5
 echo $ECHO_N "checking whether MPICH2 is declared... $ECHO_C" >&6; }
 if test "${ac_cv_have_decl_MPICH2+set}" = set; then
@@ -3686,7 +3784,7 @@ cat >>confdefs.h <<_ACEOF
 #define HAVE_DECL_MPICH2 1
 _ACEOF
 
-  MPI_DEPS="-DMPI2"
+  MPI_DEFS="-DMPI2"
 else
   cat >>confdefs.h <<_ACEOF
 #define HAVE_DECL_MPICH2 0
@@ -3753,7 +3851,7 @@ cat >>confdefs.h <<_ACEOF
 #define HAVE_DECL_MPICH2 1
 _ACEOF
 
-  MPI_DEPS="-DMPI2"
+  MPI_DEFS="-DMPI2"
 else
   cat >>confdefs.h <<_ACEOF
 #define HAVE_DECL_MPICH2 0
@@ -3820,7 +3918,7 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_mpi_main" >&5
 echo "${ECHO_T}$ac_cv_lib_mpi_main" >&6; }
 if test $ac_cv_lib_mpi_main = yes; then
-     MPI_LIBS="-L${MPI_ROOT}/lib -lmpi"
+  MPI_LIBPATH="${MPI_ROOT}/lib"
 else
      echo "libmpi not found. exiting..."
         	exit 1
@@ -3829,20 +3927,17 @@ fi
 
 fi
 
-if  [ $MPITYPE = "OPENMPI" ] ; then
-	MPI_DEPS="-DMPI2"
-elif  [ $MPITYPE = "LAM" ] ; then
-	MPI_DEPS="-DMPI2"
+if test "$MPITYPE" = "LAM" ; then
 	echo "Try to find liblam.so ..."
 	if test -f ${MPI_ROOT}/lib/liblam.so; then
         echo "Found liblam in ${MPI_ROOT}/lib"
-        MPI_LIBS="${MPI_LIBS} -llam"
+        MPI_LIBPATH="${MPI_ROOT}/lib"
 	elif test -f ${MPI_ROOT}/lib/lam/liblam.so; then
         echo "Found liblam in ${MPI_ROOT}/lib/lam"
-        MPI_LIBS="${MPI_LIBS} -llam"
+        MPI_LIBPATH="${MPI_ROOT}/lib/lam"
 	elif test -f ${MPI_ROOT}/lib64/lam/liblam.so; then
         echo "Found liblam in ${MPI_ROOT}/lib64/lam"
-        MPI_LIBS="${MPI_LIBS} -llam"
+        MPI_LIBPATH="${MPI_ROOT}/lib64/lam"
 	else
     	{ echo "$as_me:$LINENO: checking for main in -llam" >&5
 echo $ECHO_N "checking for main in -llam... $ECHO_C" >&6; }
@@ -3900,14 +3995,16 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_lam_main" >&5
 echo "${ECHO_T}$ac_cv_lib_lam_main" >&6; }
 if test $ac_cv_lib_lam_main = yes; then
-     MPI_LIBS="$MPI_LIBS -llam"
-else
-     echo "liblam not found. Probably not LAM-MPI"
+
+    	   echo "liblam not found. Probably not LAM-MPI"
 
 fi
 
 	fi
 fi
+
+fi
+## now we have found the include and lib paths and may know the type
 
 { echo "$as_me:$LINENO: checking for openpty in -lutil" >&5
 echo $ECHO_N "checking for openpty in -lutil... $ECHO_C" >&6; }
@@ -4034,10 +4131,27 @@ if test $ac_cv_lib_pthread_main = yes; then
 fi
 
 
+if test "$MPITYPE" = "OPENMPI" -o "$MPITYPE" = "LAM" ; then
+  MPI_DEFS="-DMPI2"
+fi
 
-PKG_LIBS="${MPI_LIBS} -fPIC"
-PKG_CPPFLAGS="${MPI_INCLUDE} ${MPI_DEPS} -D${MPITYPE} -fPIC"
-
+PKG_CPPFLAGS="-I${MPI_INCLUDE_PATH} ${MPI_INCL2} ${MPI_DEFS} -D${MPITYPE}"
+case "$MPITYPE" in
+  OPENMPI)
+    PKG_LIBS="-L${MPI_LIBPATH} -lmpi ${MPI_LIBS}"
+    ;;
+  LAM)
+    PKG_LIBS="-L${MPI_LIBPATH} -lmpi -llam ${MPI_LIBS}"
+    ;;
+  MPICH)
+    PKG_LIBS="-L${MPI_LIBPATH} -lmpich ${MPI_LIBS}"
+    ;;
+  *)
+    { { echo "$as_me:$LINENO: error: Unknown type of mpi: use --with-Rmpi-type or RMPI_TYPE to specify it" >&5
+echo "$as_me: error: Unknown type of mpi: use --with-Rmpi-type or RMPI_TYPE to specify it" >&2;}
+   { (exit 1); exit 1; }; }
+    ;;
+esac
 
 
 
@@ -4719,8 +4833,8 @@ OBJEXT!$OBJEXT$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
-PKG_LIBS!$PKG_LIBS$ac_delim
 PKG_CPPFLAGS!$PKG_CPPFLAGS$ac_delim
+PKG_LIBS!$PKG_LIBS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
